name: Python application

on:
  push:
    branches:
      - main  # Asegúrate de que la rama que usas sea la correcta
  pull_request:
    branches:
      - main  # También puedes usar esta configuración para PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run example_domain_logic.py
      run: python example_domain_logic.py
